---
name: Simo-Wrapper
version: 0.0301
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: 'Wrapper for Simo [DISCOURAGED]'
license: perl
resources:
  license: ~
requires:
  Encode: 2.12
  Simo: 0.0805
  Simo::Constrain: 0.0201
  Simo::Error: 0.0206
  XML::Simple: 2.18
build_requires:
  Test::More: 0
provides:
  Simo::Wrapper:
    file: lib/Simo/Wrapper.pm
    version: 0.0301
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
