---
name: Simo-Wrapper
version: 0.0205
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Object wrapper to manipulate attrs and methods.
license: perl
resources:
  license: ~
requires:
  Encode: 0
  Simo: 0
  Simo::Constrain: 0
build_requires:
  Test::More: 0
provides:
  Simo::Wrapper:
    file: lib/Simo/Wrapper.pm
    version: 0.0205
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
